#!/usr/bin/env bash
#This script displays numbers from 1 to 100, but prints different messages depending of the number

cont=1
while [ $cont -le 100 ]
do 
	if [ $((cont%15)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((cont%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((cont%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$cont"
	fi
	(( cont = cont + 1 ))
done
